### ISSUE TITLE
Home page updations and add mentor section

### ISSUE THREAD

**Issue by RajendraMallina** [RajendraMallina/code-maxima#28]
1) space between cards has to reduce like (https://www.codingal.com/   -  Choose a coding course that excites your child - section)
2)make start section 3 boxes to 1 box and add 6 lines with some dummy logos and animation text.(https://www.scaler.com/ - The Scaler Recipe, to Transform Your Career section)
3)above footer add mentor section like (https://www.scaler.com/mentor - They have something to share - section)
4)reduce space between cards in testmonals section.

**Comment by vamsi8979** [comment]
Reopening this issue for remaining changes
