### ISSUE TITLE
Add company logos section -> train style

### ISSUE THREAD

**Issue by RajendraMallina** [RajendraMallina/code-maxima#50]
1) refer(https://www.techtammina.com/) industries and technologies section.
2)Our Students got Offers in.....(logos and company name scrolling just like above website)
2)make a json with company logo and name. 
3)create company logo folder in assert to store the logo images.
4)current company names (wipro, hcl, LTI, virtusa, hexawave, ivy, cgi, fis globel, tcs, congizent, accenture, pdsl(pragmatic design solutions).

**Comment by vamsi8979** [comment]
Could not find IVY logo @RajendraMallina  Need help
