### ISSUE TITLE
Todo : work on resposiveness

### ISSUE THREAD

**Issue by RajendraMallina** [RajendraMallina/code-maxima#51]
1) add responsiveness for each section (for middle and large screens same)
2) remove animated image in the animation box section for mobile and tablets)
3) just only work for the mobile and tablet( all sections single cards for screen)

**Comment by vamsi8979** [comment]
4. also change style in review white card may be decrease font size or change image size

**Comment by vamsi8979** [comment]
6.Change  home.css to scss

**Comment by vamsi8979** [comment]
7.make home page to seperate module

**Comment by vamsi8979** [comment]
> 5. Add nth child colors for modules

Done

**Comment by vamsi8979** [comment]
> 6.Change home.css to scss

Done
